---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/tags/v0.77.1/bundle.yaml

namespace: prometheus-operator

