---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-observability-cfg
  namespace: observability
spec:
  path: ./clusters/homelab/core/observability
  sourceRef:
    kind: GitRepository
    name: homelab-repo
    namespace: flux-system
  prune: true
  interval: 10m
  # NOTE: dependsOn across across different resource kinds does not work.
  # We do a few retries instead:
  # See: https://github.com/fluxcd/flux2/discussions/1599
  retryInterval: 1m
