---
clusterName: homelab
talosVersion: v1.8.3
endpoint: https://192.168.5.2:6443
allowSchedulingOnMasters: true
additionalMachineCertSans:
  - 192.168.5.2
  - 192.168.5.3
  - 192.168.5.4
  - 100.119.181.2
  - 100.69.104.31
  - 100.106.250.118
additionalApiServerCertSans:
  - home-cluster.local

controlPlane:
  talosImageURL: factory.talos.dev/installer/62059c39988403baff7e8edbdefdbebb344bf4179a1d999ddc59ff7bb3182344
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuth}
  machineSpec:
    mode: metal
    arch: amd64
    secureboot: false
    useUKI: false

worker:
  talosImageURL: factory.talos.dev/installer/62059c39988403baff7e8edbdefdbebb344bf4179a1d999ddc59ff7bb3182344
  machineSpec:
    mode: metal
    arch: amd64
    secureboot: false
    useUKI: false
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuth}

nodes:
  - hostname: master1
    ipAddress: 192.168.5.2
    installDisk: /dev/sda
    controlPlane: true
    # NOTE: https://github.com/budimanjojo/talhelper/issues/713
    patches:
      - |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - static:
                    passphrase: ${diskEncryption}
                    slot: 0
            # ephemeral:
            #   provider: luks2
            #     - static:
            #         passphrase: ${diskEncryption}
            #         slot: 1
  - hostname: master2
    ipAddress: 192.168.5.3
    installDisk: /dev/sda
    controlPlane: true
  - hostname: master3
    ipAddress: 192.168.5.4
    installDisk: /dev/sda
    controlPlane: true
    machineSpec:
      mode: metal
      arch: amd64
      secureboot: false
  - hostname: storage1
    ipAddress: 192.168.5.5
    installDisk: /dev/nvme0n1
    controlPlane: false
    # machineDisks:
    #   - device: /dev/disk/by-id/ata-CT500MX500SSD1_2149E5EC1D9D
    #     partitions:
    #       - mountpoint: /var/mnt/sata
