---
clusterName: homelab
talosVersion: v1.9.4
endpoint: https://192.168.5.2:6443
allowSchedulingOnMasters: true
additionalApiServerCertSans:
  - home-cluster
cniConfig:
  name: none
patches:
  - |-
    cluster:
      proxy:
        disabled: true
  - |-
    machine:
      systemDiskEncryption:
        state:
          provider: luks2
          keys:
            - tpm: {}
              slot: 0
        ephemeral:
          provider: luks2
          keys:
            - static:
                passphrase: ${diskEncryption}
              slot: 0
  - |-
    - op: add
      path: /machine/kubelet/extraMounts
      value:
        - destination: /var/lib/longhorn
          type: bind
          source: /var/lib/longhorn
          options:
            - bind
            - rshared
            - rw
  - |-
    cluster:
      inlineManifests:
        - name: cilium-install
          contents: |
            ---
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
               name: cilium-install
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: cluster-admin
            subjects:
            - kind: ServiceAccount
              name: cilium-install
              namespace: kube-system
            ---
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: cilium-install
              namespace: kube-system
            ---
            apiVersion: batch/v1
            kind: Job
            metadata:
              name: cilium-install
              namespace: kube-system
            spec:
              backoffLimit: 10
              template:
                 metadata:
                  labels:
                    app: cilium-install
                spec:
                  restartPolicy: OnFailure
                  tolerations:
                    - operator: Exists
                    - effect: NoSchedule
                      operator: Exists
                    - effect: NoExecute
                      operator: Exists
                    - effect: PreferNoSchedule
                      operator: Exists
                    - key: node-role.kubernetes.io/control-plane
                      operator: Exists
                      effect: NoSchedule
                    - key: node-role.kubernetes.io/control-plane
                      operator: Exists
                      effect: NoExecute
                    - key: node-role.kubernetes.io/control-plane
                      operator: Exists
                      effect: PreferNoSchedule
                  affinity:
                    nodeAffinity:
                      requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                          - matchExpressions:
                              - key: node-role.kubernetes.io/control-plane
                                operator: Exists
                  serviceAccount: cilium-install
                  serviceAccountName: cilium-install
                  hostNetwork: true
                  containers:
                  - name: cilium-install
                    image: quay.io/cilium/cilium-cli-ci:v1.17
                    env:
                    - name: KUBERNETES_SERVICE_HOST
                      valueFrom:
                        fieldRef:
                          apiVersion: v1
                          fieldPath: status.podIP
                    - name: KUBERNETES_SERVICE_PORT
                      value: "6443"
                    command:
                      - cilium
                      - install
                      - --set
                      - ipam.mode=kubernetes
                      - --set
                      - kubeProxyReplacement=true
                      - --set
                      - securityContext.capabilities.ciliumAgent={CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}
                      - --set
                      - securityContext.capabilities.cleanCiliumState={NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}
                      - --set
                      - cgroup.autoMount.enabled=false
                      - --set
                      - cgroup.hostRoot=/sys/fs/cgroup
                      - --set
                      - k8sServiceHost=localhost
                      - --set
                      - k8sServicePort=7445

schematic:
  customization:
    systemExtensions:
      officialExtensions:
        - siderolabs/iscsi-tools
        - siderolabs/util-linux-tool
        - siderolabs/amd-ucode
        - siderolabs/amdgpu
        - siderolabs/i915
        - siderolabs/intel-ucode
        - siderolabs/mei
        - siderolabs/qemu-guest-agent
        - siderolabs/tailscale

controlPlane:
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuth}

worker:
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuth}

nodes:
  - hostname: master1
    ipAddress: 192.168.5.2
    installDisk: /dev/sda
    controlPlane: true
  - hostname: master2
    ipAddress: 192.168.5.3
    installDisk: /dev/sda
    controlPlane: true
  - hostname: master3
    ipAddress: 192.168.5.4
    installDisk: /dev/sda
    controlPlane: true
  - hostname: storage1
    ipAddress: 192.168.5.5 # + 192.168.5.6
    installDisk: /dev/nvme0n1
    controlPlane: false
    patches:
      - |-
        - op: add
          path: /machine/sysctls
          value:
            vm.nr_hugepages: "1024"
    nodeLabels:
      role: "storage-node"
    taints:
      - key: "role"
        value: "storage-node"
        effect: "NoSchedule"
  - hostname: storage2
    ipAddress: 192.168.5.7 # + 192.168.5.8
    installDisk: /dev/nvme0n1
    controlPlane: false
    patches:
      - |-
        - op: add
          path: /machine/sysctls
          value:
            vm.nr_hugepages: "1024"
    nodeLabels:
      role: "storage-node"
    taints:
      - key: "role"
        value: "storage-node"
        effect: "NoSchedule"
  - hostname: worker1
    ipAddress: 192.168.5.9
    installDisk: /dev/nvme0n1
    controlPlane: false
  - hostname: worker2
    ipAddress: 192.168.5.10
    installDisk: /dev/nvme0n1
    controlPlane: false
  - hostname: gpu1
    ipAddress: 192.168.5.11
    installDisk: /dev/sda
    controlPlane: false
  - hostname: gpu2
    ipAddress: 192.168.5.12
    installDisk: /dev/sda
    controlPlane: false
