---
clusterName: homelab
talosVersion: v1.8.3
endpoint: https://192.168.5.2:6443
allowSchedulingOnMasters: true
additionalMachineCertSans:
  - 192.168.5.2
  - 192.168.5.3
  - 192.168.5.4
  - 100.119.181.2
  - 100.69.104.31
  - 100.106.250.118
additionalApiServerCertSans:
  - home-cluster.local
patches:
  - |-
    machine:
      systemDiskEncryption:
        state:
          provider: luks2
          keys:
            - tpm: {}
              slot: 0
        ephemeral:
          provider: luks2
          keys:
            - static:
                passphrase: ${diskEncryption}
              slot: 0

controlPlane:
  talosImageURL:  factory.talos.dev/installer-secureboot/d679818c68e913b6a99dbb70319d14e91455d1c11dc6ba3ba5b2cae4a3fe9f67
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuth}

worker:
  talosImageURL: factory.talos.dev/installer-secureboot/d679818c68e913b6a99dbb70319d14e91455d1c11dc6ba3ba5b2cae4a3fe9f67
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuth}

nodes:
  - hostname: master1
    ipAddress: 192.168.5.2
    installDisk: /dev/sda
    controlPlane: true
  - hostname: master2
    ipAddress: 192.168.5.3
    installDisk: /dev/sda
    controlPlane: true
  - hostname: master3
    ipAddress: 192.168.5.4
    installDisk: /dev/sda
    controlPlane: true
    machineSpec:
      mode: metal
      arch: amd64
      secureboot: false
  - hostname: storage1
    ipAddress: 192.168.5.5
    installDisk: /dev/nvme0n1
    controlPlane: false
    # machineDisks:
    #   - device: /dev/disk/by-id/ata-CT500MX500SSD1_2149E5EC1D9D
    #     partitions:
    #       - mountpoint: /var/mnt/sata
