---
clusterName: homelab
talosVersion: v1.9.1
endpoint: https://192.168.5.2:6443
allowSchedulingOnMasters: true
additionalApiServerCertSans:
  - home-cluster
patches:
  - |-
    machine:
      systemDiskEncryption:
        state:
          provider: luks2
          keys:
            - tpm: {}
              slot: 0
        ephemeral:
          provider: luks2
          keys:
            - static:
                passphrase: ${diskEncryption}
              slot: 0
  - |-
    - op: add
      path: /machine/kubelet/extraMounts
      value:
        - destination: /var/local
          type: bind
          source: /var/local
          options:
            - bind
            - rshared
            - rw

controlPlane:
  talosImageURL:  factory.talos.dev/installer-secureboot/08086db1d88ea52b2e873f0b0c64562af7ae98f6ed83da5ee478871bbe52abd6
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuth}

worker:
  talosImageURL:  factory.talos.dev/installer-secureboot/623cd04071580f9ac9ecdc12e29da02f0c7b29f70ac776dc0368b15a0d23063d
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuth}

nodes:
  - hostname: master1
    ipAddress: 192.168.5.2
    installDisk: /dev/sda
    controlPlane: true
  - hostname: master2
    ipAddress: 192.168.5.3
    installDisk: /dev/sda
    controlPlane: true
  - hostname: master3
    ipAddress: 192.168.5.4
    installDisk: /dev/sda
    controlPlane: true
    machineSpec:
      mode: metal
      arch: amd64
      secureboot: false
  - hostname: storage1
    ipAddress: 192.168.5.5
    installDisk: /dev/nvme0n1
    controlPlane: false
    patches:
      - |-
        - op: add
          path: /machine/sysctls
          value:
            vm.nr_hugepages: "1024"
    nodeLabels:
      openebs.io/engine: "mayastor"
    # machineDisks:
    #   - device: /dev/disk/by-id/ata-ST22000NT001-3LS101_ZX21V8H5 # HDD 22TB
    #     partitions:
    #       - mountpoint: /var/local/disks/sata1
    #   - device: /dev/disk/by-id/ata-SanDisk_SSD_PLUS_480GB_24036A805360 # SSD 480GB
    #     partitions:
    #       - mountpoint: /var/local/disks/sata2
