---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook
  namespace: rook-ceph
spec:
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-operator
  namespace: rook-ceph
spec:
  releaseName: rook-operator
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: rook-ceph
  interval: 12h
  values:
    crds:
      enabled: true
    csi:
      nfs:
        enabled: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Name of the ClusterRole
  name: rook-ceph-servicemonitor
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - list
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-ceph-servicemonitor-binding
subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: rook-ceph
roleRef:
  kind: ClusterRole
  name: rook-ceph-servicemonitor
  apiGroup: rbac.authorization.k8s.io
