apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
    annotations:
        meta.helm.sh/release-name: tailscale-operator
        meta.helm.sh/release-namespace: tailscale
    labels:
        app.kubernetes.io/managed-by: Helm
        helm.toolkit.fluxcd.io/name: tailscale-operator
        helm.toolkit.fluxcd.io/namespace: tailscale
type: Opaque
data:
    client_id: ENC[AES256_GCM,data:UWYIir3yeTqV4g8G2NEkNWfAEoktt9o0,iv:Y/vzpZ88uY4RvDop+6gZFDRwnPIM6BD2qx7HLlL5PYI=,tag:nsAv4J6ZDFAganAcuIy8Fw==,type:str]
    client_secret: ENC[AES256_GCM,data:z/5eMAFStvaB6SvEhID3ouo9RybffAsiQOMllLsMuamxXVhExXUHitk/h1CEBAZla2tZDV9O1KNerD6XtayjU3z46k3Vr0sXl6JpwZFRt3yYwLT9C2wJHg==,iv:ACqLkNtGR4OS8m+XcCQRT8wI+rjphBUQ+MWV5mK9mNc=,tag:AhpFOyBQma0PoS4y51PKdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM1picnVVQ1NjZ1JKN3E0
            b1g4S0tHVUhUeUtSSUtqRUxjdGRsS0krSDBJCnRvR2U2VEpMVXZaMnlzeW85TlZn
            dmpLZ3kxY1hCamZ6YXh2SjlaMHNrUjgKLS0tIDF3SDdwZkd1Y2tDeC9sbTNYZFRQ
            bmx4VXYwZWx1bFFwTDdQR25JVHdPZXcK+c7Wlmknk3HjceJFlyY1ZqNkvnnblbN+
            HBHFFXXVsjhoG+5iu18MtIvLwaxSlTz/UQqeN3Lz3RrKirwlve9Kkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-26T08:59:15Z"
    mac: ENC[AES256_GCM,data:Ykz7wtREj9s7hiwmVWmV7UmoqjbyhqgmWBmKY7F65wu+oXdcI6kbe09/S2nk49YtdwvXFPqSmtfVYYk5Hh5e3MeaPjEr1omDZ467zT9/p2YVmazg/ums6xwJdNl7L5VjQiB+psxSo4mKsCxtYKc/65Ud5krazcyrNqPgwd68fjY=,iv:n1zCaez94StnaeYcLQUNz8/uYEfAYldPeYnIpCHReeA=,tag:ab8tUHn/FzalNhc9JLz1pw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
