---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/frzifus/ccm.git
  ref:
    branch: main

