apiVersion: v1
kind: ServiceAccount
metadata:
  name: android-view
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: android-view
  namespace: default
  annotations:
    kubernetes.io/service-account.name: android-view
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: android-view
subjects:
- kind: ServiceAccount
  name: android-view
  namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: android-view-extra
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["nodes", "storageclasses", "customresourcedefinitions", "persistentvolumeclaim", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps", "extensions", "networking.k8s.io"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets", "ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: android-view-extra
subjects:
- kind: ServiceAccount
  name: android-view
  namespace: default
roleRef:
  kind: ClusterRole
  name: android-view-extra
  apiGroup: rbac.authorization.k8s.io
