---
# NOTE: handling formating and mounting manually.
# https://github.com/siderolabs/talos/issues/8367
# https://github.com/michaelbeaumont/k8rn/blob/main/k8s/job-add-data-partition.tf
apiVersion: batch/v1
kind: Job
metadata:
  name: disk-encryption-hdd-storage1
  namespace: kube-system
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: storage1
      containers:
        - name: encrypt-disk
          image: ghcr.io/frzifus/gdisk:latest
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
            - |
              set -e
              disk=/dev/sda
              partition="${disk}1"
              partitionName=$(basename "$partition")

              passphrase=$(cat /etc/secrets/passphrase | tr -d '\n\t\r ')

              if cryptsetup isLuks "$partition"; then
                  cryptsetup luksDump "$partition"
                  echo "Data partition already exists"
                  # Check if the LUKS device is already open
                  # NOTE: Close it manually..
                  # umount "$mount_point"
                  # cryptsetup close data-crypt
                  # NOTE: reset maunally..
                  # # Wipe partition
                  # sgdisk --zap-all "${disk}"
                  # # Remove luks superblock
                  # dd if=/dev/zero of=/dev/sda1 bs=512 count=2048
                  echo "Check cryptsetup status"
                  if [[ -e "/dev/mapper/${partitionName}-encrypted" ]]; then
                      echo "LUKS device already open, skipping open step."
                  else
                      echo "Try unlocking ${partition}"
                      echo "$passphrase" | cryptsetup open "${partition}" "${partitionName}-encrypted" -
                      echo "Partition exists, opend and available at /dev/mapper/${partitionName}-encrypted"
                  fi

                  echo "Success!!"
                  exit 0
              fi

              echo "No data partition found"
              sgdisk -p "$disk"
              # Create a new partition and label it "data"
              sgdisk --new=1:0:0 --change-name=1:data --typecode=1:8300 "$disk"
              # partprobe, NOTE: missing udevadm
              sgdisk -p "$disk"

              echo -n "$passphrase" | cryptsetup luksFormat --type luks2 "${partition}" -
              echo -n "$passphrase" | cryptsetup open "${partition}" "${partitionName}-encrypted" -

              echo "Partition created, encrypted, opend and available at /dev/mapper/${partitionName}-encrypted"
          volumeMounts:
            - mountPath: /etc/secrets
              name: luks-passphrase-secret
              readOnly: true
            - mountPath: /dev
              name: dev
            - mountPath: /var
              name: var
          securityContext:
            privileged: true
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: luks-passphrase-secret
          secret:
            secretName: disk-encryption-storage1-passphrase
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: var
          hostPath:
            path: /var
            type: Directory
