apiVersion: ENC[AES256_GCM,data:lu4=,iv:XL+IH6rF3gwu1B/J5Xa5WYixsNAwlS8qj2AqVYaH/+U=,tag:eYNj44CFK0NIH6KtUJ5LtQ==,type:str]
kind: ENC[AES256_GCM,data:YdMhoHqX,iv:mgLSGCCaz90Wgf4qbrpY79yr6Hui+P2+ox5CFPi4K6Y=,tag:Af3FvNrzw2vpoPF+9Gasww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tJx5R3eNBowuyFqC4ikoAyhvsMMwy6dxcA==,iv:WlPQPl7gkzhCuaDwAkXSCqyhMhbMh9nP/E1C0hdqmOk=,tag:tVORcf97UodjPUu9pkmjqg==,type:str]
    namespace: ENC[AES256_GCM,data:dfCDK58n4Yw=,iv:89OQT3cGQsnZL+7UkaID4kb/APKdN/UBsSVYrCUrkAc=,tag:qlgJjihDRC0zK4KEErsUsg==,type:str]
type: ENC[AES256_GCM,data:pGJlUFoJ,iv:7qRIOhifvlw4Ew5XLiiLD9kIydt66J5lhV0343y7Gpo=,tag:5GUIuAbvrIN9AzqLFlZJQQ==,type:str]
stringData:
    SERVER1_NAME: ENC[AES256_GCM,data:Z3k7,iv:UpWYRzel9Zx8QnQFgZi336xlY/iQhP5quqM1rWnGVOU=,tag:bqjApUEAczvu0pSi8JBOkQ==,type:str]
    SERVER1_HOST: ENC[AES256_GCM,data:V24Cc9AI6NTinGa6tA+sLRlhMVPOxoU=,iv:VkqGUyyHFdjlSw6E4LMk7teeZaKrmUdDm8QsRYc5Dx4=,tag:nxRWm/OvCWyD21CY2JOCoA==,type:str]
    SERVER1_USERNAME: ENC[AES256_GCM,data:C+1K+1vK2A==,iv:6HQFwFYHBpLIsgWgppnh8vCsl6yWRzicVwm5n4HH1NM=,tag:GvfMyk6yDd1PqPbjxn22Tw==,type:str]
    SERVER1_PASSWORD: ENC[AES256_GCM,data:xvl43CcY5Bov1sc=,iv:ZBB73NrOlx4ZQPbWS/JQPq/7HiYWpz9BpYMkjm4aX8w=,tag:GqzcKdwROKs758rr7wXvVA==,type:str]
    SERVER2_NAME: ENC[AES256_GCM,data:ix7CuPAJNtt/bcY7bQ==,iv:/7bCfghq2frv3/xFxHjdqWDt4ruupu6io6E6/f/TCzg=,tag:pZ4P4kw2SMvGilkyrRor1g==,type:str]
    SERVER2_HOST: ENC[AES256_GCM,data:0pA0RLcAjkyJYm5Zw3fiIkGdnElA,iv:ea4Fy+0J2q76GULnfB5LsRAVT1kXO4H5vGGaaVeHPhc=,tag:E2ISJY7jH867+2Ut1a67Fg==,type:str]
    SERVER2_USERNAME: ENC[AES256_GCM,data:p2p9QBA2XQ==,iv:hl566pQNl4hWtvxS4Xamp4KkBjRQhboJiRv5PyRSYJw=,tag:FIJytCVssEXkC1UUdqUf+w==,type:str]
    SERVER2_PASSWORD: ENC[AES256_GCM,data:fe20El6IwurA5sw=,iv:H677BnRknt3GFL4V4DoNQY+cAUG1xGg9invgcCdRVCQ=,tag:pzeFKquAniJk2mH3yRNhvw==,type:str]
    FEED1_NAME: ENC[AES256_GCM,data:9Adj8m4XVdLnG4Qx,iv:UJSCRyObtBsrmYy5yGnQUzEKJSZikjvzJjQjtMyieR4=,tag:M0W4fDzvBkuq9vPsYS6Urg==,type:str]
    FEED1_URL: ENC[AES256_GCM,data:cMjxevtyp8S+pxEcFJjmTXAgXD6sL3LxATym9FWsYbk2VdPqDZOnujRMsL2KQ08ETlr2RdgZHNIlwBEpKLiYIWLUxODOzL1CR+M/c7S8/ovKMH2AVA==,iv:giQneujfKfqW2IEbURIIZWKQ+evOblm2AfnmH37De4M=,tag:zkYakCtvO6GFmSO9xVbcUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdjFEWUpENFY0K2QrdUVh
            VVNycUUySERBVjRPYm9pVFNkc3ZwMVMrVlZZCmNCL1lyb1dpZGRoaDZhNFlzRXdB
            a25rS24rVTVxb1BIeTRSSWxZM2tvSEkKLS0tIE1hdXQzRHkvdnYzVThtZFRZN0pJ
            RndCRnFvYXBuS2lEZG0zbU52NjVCT28KFQrI9ihYJ3t0Tyj3P8mz4QnYG7ujDFRo
            h9qXoHDhpqXsHP2VexrHeVmNj9XOUCLuRiOkmC3VgeCEWkiZU2BVcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T22:43:24Z"
    mac: ENC[AES256_GCM,data:mBe9qOu/xYsZFv+fVq1A/KNEnfr10X5IPoMctwFWynvYe1AQy1i1j63a7K62zx+wViKAL1pBByoZ5aTtJ2Drmw3F4djztbw+0U5X1jDURVMAmggZvQLNjYAF015p4PtyzBDxZ09LL2Kvrve9jJUBOJam4T7ABC+sfyaOi9zvJmo=,iv:IQg/fwHNGh4aqZgB+tH2MDdB+9bZ0SJJmwk3km53yws=,tag:Ns0ikxilwopPrkt9CMWdVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
