---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 5m
  chart:
    spec:
      chart: jellyfin
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  install:
    createNamespace: true
  values:
    persistence:
      enabled: true
      storageClass: "standard"
      size: 10Gi
    service:
      type: ClusterIP
      port: 8096
