---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jellyfin-pvc-config
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.109.204.207
    path: "/"
  mountOptions:
    - nfsvers=4.2
  storageClassName: nfs-storage1-jellyfin-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-config
  namespace: jellyfin
spec:
  storageClassName: nfs-storage1-jellyfin-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jellyfin-pvc-data
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-storage1-jellyfin-data
  capacity:
    storage: 180Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.109.204.207
    path: "/"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-data
  namespace: jellyfin
spec:
  storageClassName: nfs-storage1-jellyfin-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 180Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-db
  namespace: jellyfin
spec:
  storageClassName: openebs-single-replica-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config
  namespace: jellyfin
spec:
  storageClassName: openebs-single-replica-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
