---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
#  - storage
  - tailscale
# - gpu

resources:
  - metrics-server.yaml
  - kepler.yaml
  - cert-manager.yaml
  - nginx-ingress.yaml
  - storage/openebs.yaml
  - storage/disks.yaml

#  - metallb.yaml
#  - model-validation-controller.yaml
#  - observability.yaml
#  - grafana-dashboards.yaml
