---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 18.2.4
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  install:
    createNamespace: true
  values:
    replicaCount: 3
    service:
      type: ClusterIP
