# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: openebs-nfs-storage1
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: simple-large-media-hdd
  namespace: openebs
spec:
  node: storage1
  disks: ["/dev/disk/by-id/ata-ST22000NT001-3LS101_ZX21V8H5"]
  topology:
    labelled:
      type: media
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-single-replica-media-hdd
parameters:
  protocol: nvmf
  repl: "1"
  thin: "true"
  fsType: xfs
  poolAffinityTopologyLabel: |
    type: media
allowVolumeExpansion: true
provisioner: io.openebs.csi-mayastor
reclaimPolicy: Delete # Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-media-hdd-1
  namespace: openebs
  labels:
    app: nfs-pv-media-hdd-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti
  storageClassName: openebs-single-replica-media-hdd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-media-hdd-2
  namespace: openebs
  labels:
    app: nfs-pv-media-hdd-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti
  storageClassName: openebs-single-replica-media-hdd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
  namespace: openebs
spec:
  replicas: 1 # NOTE: Must because of RWO
  serviceName: "nfs-storage1-hdd"
  selector:
    matchLabels:
      app: nfs-server-storage1
  template:
    metadata:
      labels:
        app: nfs-server-storage1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - storage1
      initContainers:
      # - name: set-permissions
      #   image: busybox
      #   command: ["sh", "-c", "chmod 777 /export"]
      #   volumeMounts:
      #   - name: nfs-data
      #     mountPath: /export
      containers:
      - name: ganesha-nfs
        image: ghcr.io/frzifus/ganesha-nfs:latest
        ports:
        - containerPort: 2049 # NFSv4 default port
          name: nfs
        resources:
          requests:
            memory: "1Gi"
            cpu: "125m"
          limits:
            memory: "4Gi"
            cpu: "2.5"
        volumeMounts:
        - name: nfs-data-1
          mountPath: /export/part-1 # Mount PVC to export directory
        - name: nfs-data-2
          mountPath: /export/part-2 # Mount PVC to export directory
        securityContext:
          privileged: false
        env:
        - name: GANESHA_LOGFILE
          value: "/var/log/ganesha.log" # Log file location
        - name: GANESHA_CONFIGFILE
          value: "/etc/ganesha/ganesha.conf" # Config file location
        - name: GANESHA_OPTIONS
          value: "" # Add options if necessary
        - name: GANESHA_EPOCH
          value: "1" # Ganesha epoch value
        - name: GANESHA_EXPORT_ID
          value: "101" # Unique export ID
        - name: GANESHA_EXPORT
          value: "/export" # Export location matching the PVC mount
        - name: GANESHA_ACCESS
          value: "*" # Allow access from all clients
        - name: GANESHA_ROOT_ACCESS
          value: "*" # Allow root access from all clients
        - name: GANESHA_NFS_PROTOCOLS
          value: "4.2" # Enable NFSv4
        - name: GANESHA_TRANSPORTS
          value: "TCP" # Use TCP for transport
        - name: GANESHA_BOOTSTRAP_CONFIG
          value: "yes" # Write fresh config file on start
        - name: GANESHA_GRACELESS
          value: "true" # Disable NFSv4 grace period
      volumes:
        - name: nfs-data-1
          persistentVolumeClaim:
            claimName: nfs-pv-media-hdd-1
        - name: nfs-data-2
          persistentVolumeClaim:
            claimName: nfs-pv-media-hdd-2

---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server-storage1
  namespace: openebs
spec:
  selector:
    app: nfs-server-storage1
  clusterIP: 10.109.204.207
  ports:
    - name: nfs
      port: 2049
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-openebs-single-replica-media-rwx
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.109.204.207
    path: "/"
  mountOptions:
    - nfsvers=4.2
