---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 1h
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mayastor
  namespace: openebs
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 1h
  targetNamespace: openebs
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
      version: 4.1.1
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
    mayastor:
      csi:
        node:
          # currently necessary because the init container checks for nvmeof module but Talos compiles it in
          initContainers:
            enabled: false
      etcd:
        replicaCount: 3
      eventing:
        enabled: false
      io_engine:
        # It's the automatic mode, in the DPDK code IOVA_MODE_DC, that causes issues.
        # Confirmed by EAL debug log output that this really selects VA
        envcontext: "iova-mode=va"
      loki-stack:
        enabled: false
      obs:
        callhome:
          enabled: false
      storageClass:
        # we can't override reclaimPolicy so just make the classes explicit in base-config
        enabled: false
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: simple-small-cache-ssd
  namespace: openebs
spec:
  node: storage1
  disks: ["/dev/disk/by-id/ata-SanDisk_SSD_PLUS_480GB_24036A805360"]
  topology:
    labelled:
      type: cache
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-single-replica-cache-ssd
parameters:
  protocol: nvmf
  repl: "1"
  thin: "true"
  fsType: xfs
  poolAffinityTopologyLabel: |
    type: cache
allowVolumeExpansion: true
provisioner: io.openebs.csi-mayastor
reclaimPolicy: Delete # Retain
